name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      RUBYOPT: "--enable=frozen-string-literal"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # Runs also bundle install

      - name: Run tests
        run: bundle exec rake
